### ISSUE TITLE
Crashing when selecting "Editor"

### ISSUE THREAD

**Issue by Sandra-UwU-neko** [cengelha/NomNom#3] opened 2020-07-19 11:35 UTC
![image](https://user-images.githubusercontent.com/23656101/87873758-4bc20180-c9c4-11ea-8778-7abcb7acb247.png)

[report.txt](https://github.com/cengelha/NomNom/files/4943629/report.txt)

That should be everything you need ^^

**Comment by cengelha** [comment] 2020-07-19 15:59
Could it be possible that you manually deleted the "TeleporterEndpoints" entry? That shouldn't happen if it's in there like the game dictates.

**Comment by Allesanddro** [comment] 2020-07-19 16:13
well idk i used didnt edited that much if i did so is there a way to revert it?

**Comment by cengelha** [comment] 2020-07-19 20:45
Saving again in-game should fix it. Could you attach the JSON of it here (Save to JSON)? Then I can have a look at it.

**Comment by Allesanddro** [comment] 2020-07-20 08:57
Will do when I'm back at home

**Comment by Allesanddro** [comment] 2020-07-21 09:41
so uh were does the json file gets saved?

**Comment by cengelha** [comment] 2020-07-21 12:25
In the "json" folder in the output path. You can open it diretly from the manager page by clicking the open-folder icon next to the path.

**Comment by Allesanddro** [comment] 2020-07-21 14:07
they r empty 
https://pastebin.com/raw/VYbwbC40

**Comment by webmaster442** [comment] 2020-07-21 15:49
I can confirm the issue. Prior to experiencing this I deleted the teleporter and placed a new one on my 1st starting base. Stack trace for exception in my case: `System.NullReferenceException`

Game version: Latest steam version.
```
at:  NomNom.ViewModel.EditorDiscoveryViewModel.get_JsonTeleportEndpoints() hely: C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\EditorDiscoveryViewModel.cs, line: 51
at:  NomNom.ViewModel.EditorDiscoveryViewModel.FillCollection() hely: C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\EditorDiscoveryViewModel.cs, line: 633
at:  NomNom.ViewModel.EditorDiscoveryViewModel..ctor() hely: C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\EditorDiscoveryViewModel.cs, line: 621
at:  NomNom.ViewModel.EditorViewModel..ctor() hely: C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\EditorViewModel.cs, line: 81
at:  NomNom.ViewModel.MainViewModel.NavigateToEditor() hely: C:\Users\cenge\source\repos\NomNom\NomNom\ViewModel\MainViewModel.cs, line: 257
at:  MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
at:  System.Windows.Controls.Primitives.ButtonBase.OnClick()
at:  System.Windows.Controls.Button.OnClick()
at:  System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at:  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at:  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at:  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at:  System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at:  System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
at:  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at:  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at:  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at:  System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at:  System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at:  System.Windows.Input.InputManager.ProcessStagingArea()
at:  System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at:  System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at:  System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at:  System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at:  System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at:  MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at:  MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at:  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at:  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Json output just writes a null to the export.

**Comment by cengelha** [comment] 2020-07-21 20:00
Alright. Starting with the next version it will be more restrive with this and wont allow such files to load but maybe showing them in the selection marked as invalid in an additional column.
Can any of you attach a save that will trigger this error?

**Comment by webmaster442** [comment] 2020-07-21 20:21
I try to create an other save. After playing a litle bit more & doing some quests my save file appears to be fixed, It's openable again without issues

**Comment by cengelha** [comment] 2020-07-21 20:46
Got it now on one of my own saves. Seems to be indeed a problem when it tries to load the existing but empty list of "TeleportEndpoints" which should only be a problem with a freshly started save when you haven't yet created a base or visited a space station.
It will not be deserialized to an empty list but to "null" and therefore throw this exeption. As I have a save to reproduce it now, I will find a way to fix it. 
But the new restrictions will come nonetheless as I already wasn't that happy with the current way.

**Comment by cengelha** [comment] 2020-07-21 20:55
Or not. It was an other error caused by not executed/commented code to trace an other issue... Save is still need

**Comment by Allesanddro** [comment] 2020-07-22 09:59
https://workupload.com/file/DeZY2Sn7X7s

**Comment by cengelha** [comment] 2020-07-22 22:40
Thanks @Allesanddro! The stack trace was actually a false trace. That ViewModel is just the first one that is loaded and therefore shown... 
The actual problem was a false data type for an entry in the file. Hadn't set the "MultiplayerLobbyID" to anything else than the default (0) in my saves but it could also be as seed (text) as in yours. Fixed in the next version. The "null" in the json was the same that caused this exception

Currently working on the restrictions mentioned above and one a good way but will probably still need some days to finish (the next version).

**Closed** 2020-08-28 18:06 UTC
Labels: bug
