### ISSUE TITLE
[Bug] Crashing on startup of NomNom...

### ISSUE THREAD

**Issue by Jayshua83** [cengelha/NomNom#34] opened 2021-02-02 08:20 UTC
Crashing on startup of NomNom...

[NomNom.zip](https://github.com/cengelha/NomNom/files/5909646/NomNom.zip)

**Comment by ac1111532** [comment] 2021-04-02 21:11
Bump, Having Same Problem

**Comment by cengelha** [comment] 2021-04-03 21:00
I'll have a look at it

**Comment by mikey1975** [comment] 2021-04-09 07:40
Good day,
Suddenly same problem.

Hope below can help a bit.

[NomNom 3.1.0.15-alpha.15 Crash Report.txt](https://github.com/cengelha/NomNom/files/6283976/NomNom.3.1.0.15-alpha.15.Crash.Report.txt)

**Comment by grafvonzan** [comment] 2021-04-10 04:39
Same issue here. Here are the crash reports.

[startup_crash_reports.zip](https://github.com/cengelha/NomNom/files/6289227/startup_crash_reports.zip)

**Comment by cengelha** [comment] 2021-05-29 22:58
@Jayshua83 Can you send me your save folder if they still produce this crash? Yours is different than the others posted here and in other issues. I need to debug it to be sure it will be fixed in the next version but can't reproduce it with my files.

**Closed** 2021-06-26 16:37 UTC
Labels: bug
